/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPromotersRouteImport } from './routes/_app.promoters'
import { Route as AppMensalRouteImport } from './routes/_app.mensal'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEventosIndexRouteImport } from './routes/_app.eventos.index'
import { Route as AppEventosEventIdRouteImport } from './routes/_app.eventos.$eventId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPromotersRoute = AppPromotersRouteImport.update({
  id: '/promoters',
  path: '/promoters',
  getParentRoute: () => AppRoute,
} as any)
const AppMensalRoute = AppMensalRouteImport.update({
  id: '/mensal',
  path: '/mensal',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosIndexRoute = AppEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosEventIdRoute = AppEventosEventIdRouteImport.update({
  id: '/eventos/$eventId',
  path: '/eventos/$eventId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/mensal': typeof AppMensalRoute
  '/promoters': typeof AppPromotersRoute
  '/eventos/$eventId': typeof AppEventosEventIdRoute
  '/eventos/': typeof AppEventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/mensal': typeof AppMensalRoute
  '/promoters': typeof AppPromotersRoute
  '/eventos/$eventId': typeof AppEventosEventIdRoute
  '/eventos': typeof AppEventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/mensal': typeof AppMensalRoute
  '/_app/promoters': typeof AppPromotersRoute
  '/_app/eventos/$eventId': typeof AppEventosEventIdRoute
  '/_app/eventos/': typeof AppEventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/financeiro'
    | '/mensal'
    | '/promoters'
    | '/eventos/$eventId'
    | '/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/financeiro'
    | '/mensal'
    | '/promoters'
    | '/eventos/$eventId'
    | '/eventos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/mensal'
    | '/_app/promoters'
    | '/_app/eventos/$eventId'
    | '/_app/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/promoters': {
      id: '/_app/promoters'
      path: '/promoters'
      fullPath: '/promoters'
      preLoaderRoute: typeof AppPromotersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mensal': {
      id: '/_app/mensal'
      path: '/mensal'
      fullPath: '/mensal'
      preLoaderRoute: typeof AppMensalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos/': {
      id: '/_app/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AppEventosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos/$eventId': {
      id: '/_app/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof AppEventosEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppMensalRoute: typeof AppMensalRoute
  AppPromotersRoute: typeof AppPromotersRoute
  AppEventosEventIdRoute: typeof AppEventosEventIdRoute
  AppEventosIndexRoute: typeof AppEventosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppMensalRoute: AppMensalRoute,
  AppPromotersRoute: AppPromotersRoute,
  AppEventosEventIdRoute: AppEventosEventIdRoute,
  AppEventosIndexRoute: AppEventosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
